# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Khamutov
tagline:          'A Jekyll theme'
description:      'Software engineer, architect Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://khamutov.github.io

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

# Custom vars
version:          0.1.2

github:
  repo:           https://github.com/khamutov/khamutov.github.io

gems:
  - jekyll-paginate
  - jekyll-sitemap
